### ISSUE TITLE
Change blurb text which accompanies Six Acts logo in preview when sharing link on facebook

### ISSUE THREAD

**Issue by EvaSchlunke** [pdiveris/sixacts#110]
![fbook](https://user-images.githubusercontent.com/53023979/62456113-a6d8f500-b76f-11e9-822e-7e203aab9525.JPG)

Current visible text reads:
'Minimum gap of 20%, V narrow, 'first-past-the-post', voting results (eg 51% vs 49%) lead to deep national divisions that do not reflect real consensus. Fundamental high consequence...'

Can we change this to:
'The Six Acts proposals and voting site where you'll be able to input into the idea pool for radical democratic action.'
??

**Comment by pdiveris** [comment]
Oh, you lost me. OK. I don;t know where that's from. Facebook must have cached an old version of the banner image. I am note sure I can ask them to re-fresh it but I wll try.

Let me explain. When a URL is pasted in a message, post or other thing in Facebook, Facebook sends out a reader bot which fetches the contents of the URL and caches a rendered preview of it, which it then uses for it perpetually. I have a great fear that it is very hard to get them to refresh that cached version, but I will have a look. You see, the benefits of Github tickets, all this time I thought you were talking about the splash page. I had no idea what you were referring to!

**Comment by EvaSchlunke** [comment]
I suspected that it would be semi-out-of-our-hands, so if it's going to be a time intensive excercise lets not worry about it, but please have a quick try anyway.

Totally agree that messaging you requests such as this are counter-productive if misunderstood and must be avoided! (I was reacting to somebody else's impatience and not thinking straight)

**Comment by pdiveris** [comment]
OK, I am afraid I have no control over this. Apparently it will fix itself over time..
