### ISSUE TITLE
What does 'Can't persist vote' indicate?

### ISSUE THREAD

**Issue by EvaSchlunke** [pdiveris/sixacts#123]
![can't persist vote](https://user-images.githubusercontent.com/53023979/62711616-46f18100-b9f1-11e9-9a38-b42937ebee46.JPG)

Unsure why some proposals won't allow me to add a 'dislike' and what the '_Can't persist vote_' message indicates when this happens.

I can't see any pattern for why I am able to 'dislike' some proposals and not others

I thought maybe it was because they were proposals submitted by my username and a user is unable to dislike their own proposals? 

If this is the case, can we change the _'Can't persist vote'_ pop-up message to something like:
_'You cannot dislike your own proposal'_
Which is much clearer to the user.

**Comment by pdiveris** [comment]
It means that there was aproblem in registering the vote. You need to tell me what you clicked (vote or dislike) and which proposal.

**Comment by pdiveris** [comment]
But I think I know when that happens and it's something I am working on - it's a race condition when a record is left with no vote and dislike, when in fact it should have been removed.

**Comment by pdiveris** [comment]
I am closing this and adding it as bug as it's not a label thing but a race condition.

**Comment by EvaSchlunke** [comment]
Ok. Just to clarify - All vote added and removed functions are working perfectly. This issue only relates to the dislike function.

**Comment by pdiveris** [comment]
Yes sure. As I said, it's a race condition of which I am aware and which I really need to fix!
