### ISSUE TITLE
Race condition 'cannot persist vote'

### ISSUE THREAD

**Issue by pdiveris** [pdiveris/sixacts#124]
It seems to happen when after a series of transactions a ghost record is left for the user with no votes and no dislikes when thsi record should be just removed.

Additionally, the ruleset for voting doesn't seem to catch the condition and ends the loop with an unhelpful message.

**Comment by EvaSchlunke** [comment]
I have attempted to dislike all of the 8 existing proposals.

4 of them allowed me to 'dislike' and pop-up message corresponded correctly.
The other 4 (Minimum Gap, Ban extra-political, Independent court, and make EC accountable) produced the 'Can't persist vote' pop-up and would not add my dislike.

**Comment by pdiveris** [comment]
That's helpful, thank you.

**Comment by pdiveris** [comment]
Hey @EvaSchlunke, can you test this at some point and if it works for you close the issue please?

**Comment by pdiveris** [comment]
I am closing this as I've tested it thoroughly. Do re-open if you find it not working.

**Comment by EvaSchlunke** [comment]
Confirmed. Working beautifully now.
