### ISSUE TITLE
Social media icon for Six Acts facebook links to twitter

### ISSUE THREAD

**Issue by EvaSchlunke** [pdiveris/sixacts#140]
![fbook link](https://user-images.githubusercontent.com/53023979/62789148-3f4cdd80-bac0-11e9-84d3-0e5a10efcf15.JPG)

Can we correct so fbook icon links to Six Acts fbook (not twitter)

The twitter icon links correctly to Six Acts twitter
All the sharing links on individual proposals are working fine.

**Comment by pdiveris** [comment]
Sure, what's the facebook link please?

**Comment by EvaSchlunke** [comment]
https://www.facebook.com/groups/899694013703882/
