### ISSUE TITLE
feature-document: Add links and produce document

### ISSUE THREAD

**Issue by pdiveris** [pdiveris/sixacts#149]
#### Add links as disuscced in #75 
* most votes
* most recent
* top six

Let's examine later whether we want the sidebar, or we want the odcument ot be full page width.

**Comment by EvaSchlunke** [comment]
Wondering if we can keep this as simple as possible...

Can we arrange it so that the view when filtered as most votes or most recent it appears as just a re-ordering of the master list?
![masterlist](https://user-images.githubusercontent.com/53023979/62807305-f95a3e80-baec-11e9-9296-3f518de0d94d.JPG)

and when it's the topsix only six of them appear...
![top six](https://user-images.githubusercontent.com/53023979/62807485-6968c480-baed-11e9-9a5e-4c68e75ffc27.JPG)

**Comment by pdiveris** [comment]
Erm.. sort of. That's kind of what I am doing - however, in the Top Six it might be useful to have them expanded. Let me know asap because if you don't wnat them expanded then it's a piece od cake. I mean it can be done in 10 minutes.

**Comment by pdiveris** [comment]
ps: we can of course add a tag like label at the top of the document indicating the mode.

**Comment by EvaSchlunke** [comment]
Is it possible to have them unexpanded but with the 'expand' option available? As they appear above?

A tag-like label at top - would this be where you can see and select the filter/reorder options?

**Comment by pdiveris** [comment]
The plus button is there to stay, I am not removing them. Unfortunately I have already done tons of worl to put the filters below the categories on the lsft sidebar. Wait to see it and and if you really don't like it I'l' change it. I am actually done with it, will deploy in next 20 minutes.

![Screenshot 2019-08-09 at 23 54 08](https://user-images.githubusercontent.com/1022373/62813127-07b25580-bb01-11e9-91e0-abd238c1f9ce.png)

**Comment by pdiveris** [comment]
OK so this is more or less done. Perhaps it might be useful to add a label or other indicator at the top showing the "mode" i.e. "Current Document" "Most Voted" etc. 

Let me know.

**Comment by EvaSchlunke** [comment]
Looks good. Don't think it needs anymore labelling, but would it be possible to change the state of the active label?
Eg. When viewing 'Most recent' the view by button is **bolder** than the others?

Also, just for consistency - could we order the 'current document' proposals so they correspond with the order that the categories appear in sidebar? 
**Proposal for Voting Systems
Proposal for Economic and Financial
Proposal for Quality of info
Proposal for Governance and conduct
Proposal for Citizen participation
Proposal for Other**

_Final point:_ In the early stages of poll when we do not yet have proposals for each category, the 'current document' would have spaces where the yet-to-be-added proposals will appear. Eg
**Proposal for Voting Systems
(space)
Proposal for Quality of info
Proposal for Governance and conduct
(space)
Proposal for Other**

**Comment by pdiveris** [comment]
The answer to both is yes, In fact, the bold button was already planned. Will open two new separate tickets asap.
