### ISSUE TITLE
Further edits required to text on static 'About' page

### ISSUE THREAD

**Issue by EvaSchlunke** [pdiveris/sixacts#159]
[Further edits to about.pdf](https://github.com/pdiveris/sixacts/files/3489006/Further.edits.to.about.pdf)

Resending edits, with some new additions (all changes needed are to section in red)
These need to be made to the sixacts.org website as they contatin vital pre-launch information for users about how the poll will be conducted.

**Comment by pdiveris** [comment]
This has now been fixed, pls check beta and live and CLOSE the issue as it's holding me from merging into my current branch and carrying out more work (on error handling which I really need to complete.)

**Comment by pdiveris** [comment]
OK, I am closing this as it's stopping me from working in other parts of the syste, specfically the Eror Handling which is **crucial**. Feel free to re-open it if you don't think it's solved.
