### ISSUE TITLE
Reorder categories in accord with the original document

### ISSUE THREAD

**Issue by pdiveris** [pdiveris/sixacts#169]
Reorder categories in accord with the original document.

**Comment by pdiveris** [comment]
Hi Eva, can you please re-send me any document with the order in it? Can't find them!

**Comment by pdiveris** [comment]
Is this the order?

![image](https://user-images.githubusercontent.com/1022373/62834663-929d6800-bc47-11e9-8347-f723adafaf8e.png)

**Comment by EvaSchlunke** [comment]
![catsnip](https://user-images.githubusercontent.com/53023979/62834936-ae563d80-bc4a-11e9-83ac-9d73090248a7.JPG)
Above is the order that people are now familiar with - so should we make this the official order now?

This will mean reordering them here
![catsnip2](https://user-images.githubusercontent.com/53023979/62835035-9206d080-bc4b-11e9-88a2-8c7d39f8cb93.JPG)


**Also, lets use this exact wording in all instances - (without 'Reforms for')**
Voting and Voting Systems
Government Structures and Conduct of Elected Representatives
Ensuring the Accuracy of Political Information
Economic and Financial Influences
Citizen Participation
Other

**Comment by pdiveris** [comment]
Government Structures and Conduct of Elected Representatives is far too long. I will have to change the whole grid layout.

**Comment by EvaSchlunke** [comment]
Yes, I just spotted that now too.
How about 'Government structures and conduct'

**Comment by pdiveris** [comment]
OK, let me try.

**Comment by EvaSchlunke** [comment]
Or an easier fix would be to change the Categories Explained doc to:
Governance and political conduct

Lets just do that. Sorry!!!

**Comment by pdiveris** [comment]
OK.

**Comment by EvaSchlunke** [comment]
Thanks x
