### ISSUE TITLE
Email reset link 

### ISSUE THREAD

**Issue by jondeluge** [pdiveris/sixacts#17]
Password reset request received ok
rlink results in:
sixacts.div’s server IP address could not be found.
windows and android

**Comment by pdiveris** [comment]
Looking into it, thank you.

**Comment by pdiveris** [comment]
This should be fixed now. Please check and close the issue if you too find it fixed. If not use this space to explain (or fb me!)

BTW the issue related to my having accidentally mixed the dev enironment's emal configurationand you reported it pretty much at the same time as I was adding issue #18  related to automated backups!

On another note, you can cross reference issues in these comments here by hitting the hash symbol - this will you a popup list of issues.

**Comment by pdiveris** [comment]
I am closing this my self due to inaction and conviction.

**Comment by jondeluge** [comment]
ok. im on slow. J
-- 
Jon Large
07890 104323
nemo@backtothetrees.org
