### ISSUE TITLE
Migrate the new filter method across to all consumer pages

### ISSUE THREAD

**Issue by pdiveris** [pdiveris/sixacts#181]
Migrate the new filter method across to all consumer pages. We are _filtering_! Well, in two minutes!

**Comment by EvaSchlunke** [comment]
'Most votes' and 'most recent' working perfectly.

'Current document' displays identically to 'Most votes' so this needs looking at.

At this point in time a 'Current document' view should look like this:
[Curent doc.pdf](https://github.com/pdiveris/sixacts/files/3503784/Curent.doc.pdf)

But I've noticed there is a problem when there are 2 or more leading proposals in each category with the same number of votes... Should we include all of them on the current doc?  If we do this it would mean that at times the current document will have more than six proposals. (as shown in the attached PDF)

I will need to think about how to deal with this. Do you have any ideas?

**Comment by pdiveris** [comment]
Yes, no. Current document is only six items long, that's all. But I agree, it feels like doing nothing. I am looking at all this Scheiße.

Petros Diveris
Sent from Manchester with utter care

E: petros@diveris.org (mailto:petros@diveris.org)
P: +44 7771 608 617 (tel:+44%207771%20608%20617)+44 (0) 161 249 0536 (tel:+44%20(0)%20161%20249%200536) (Fax)
W: http://www.diveris.org

**Comment by EvaSchlunke** [comment]
If this is time consuming and fiddly we can postpone the 'current document' view until post-launch.
This is not an essential feature for launching and can be added later.

**Comment by pdiveris** [comment]
It's more complicated. Will explain, I am done with it, just tidying up now.

Petros Diveris
Sent from Manchester with utter care

E: petros@diveris.org (mailto:petros@diveris.org)
P: +44 7771 608 617 (tel:+44%207771%20608%20617)+44 (0) 161 249 0536 (tel:+44%20(0)%20161%20249%200536) (Fax)
W: http://www.diveris.org
