### ISSUE TITLE
Author / user doesn't appear on main site - 'posted by' blank

### ISSUE THREAD

**Issue by EvaSchlunke** [pdiveris/sixacts#183]
New users to the site (those with access via 'campaigners' link) are not being displayed as authors on mainsite.

The proposals submitted by new users are displaying correctly, but there is a blank where the username should appear.
Eg. Posted by: [blank]

Username appears in nova site, so the issue appears to be with the display on mainsite rather than loss of data.

**Comment by pdiveris** [comment]
Yep, fixed.

**Comment by EvaSchlunke** [comment]
2 new submissions not displaying author.

**Comment by pdiveris** [comment]
Oh, I must have only copied on beta. Let me check.

**Comment by pdiveris** [comment]
Yeah, it's me. I have an automated system deploying and I accidentally targeted beta, not the live site. Ouch.

**Comment by EvaSchlunke** [comment]
THat's better, names appearing now, thanks : )
