### ISSUE TITLE
Program a freeze-count moment from 5pm to 5:30pm 17th Aug

### ISSUE THREAD

**Issue by EvaSchlunke** [pdiveris/sixacts#185]
We will give users an initial one-hour period of activity to submit and vote on proposals from 4pm to 5pm, 17th Aug.

At 5pm we will need to freeze voting for up to 30 mins (probably less) while we record the leading 6 proposals and announce the 'current document'.

Can we suspend voting and submitting activity for a 15 - 30 min period while this takes place?

**Comment by pdiveris** [comment]
OK, that's done beautifully. It can be achieved by any of us 3 at any tome for a max of 30 minutes as follows:

* Visit the URL https://www.sixacts.org/pause. If the site was paused, it will unpause.
* Visit the same URL and will switch to the opposite.

If left alone if till time out the freee in 30 minutes! I am deploying on both, you can test on beta!

**Comment by pdiveris** [comment]
I take it the freeze isfor both, voting and adding proposals?
