### ISSUE TITLE
Can't log in to profile - Won't accept password

### ISSUE THREAD

**Issue by EvaSchlunke** [pdiveris/sixacts#188]
Users are unsure how /unable to change their display name.

The link to account/profile in the verification email takes user to a log-in window.
![login to profile2](https://user-images.githubusercontent.com/53023979/63201656-1effbe80-c07e-11e9-81cf-d409600af0aa.JPG)

When I enter or select my email account the password box fills automatically with an auto-generated password.
![login to profile](https://user-images.githubusercontent.com/53023979/63201652-1a3b0a80-c07e-11e9-9986-a5e2946f50c6.JPG)
If I select this by hitting log-in, the text boxes empty and I am prompted to start process again.

If I select 'forgot your password?' and follow the link sent to my email I get this text box.
![login to profile3](https://user-images.githubusercontent.com/53023979/63201661-258e3600-c07e-11e9-88b3-e2a368e7f750.JPG)

When I change pword and hit 'reset password' I get '500 Server error' screen.

**Comment by pdiveris** [comment]
1. The long window is chrome, is not me.
2. Click on the top right where it says login
3. Type in your email and password.
4. Click on the icon on the tot right.

You are in your profile. I just logged in as you.

**Comment by pdiveris** [comment]
I've reopend this for you to confirm. The ticket came in as I had just finished the password branch and all of a sudden I ended up with two separate streams, both of which broke as I was restoring due to panic. It should as intented now.
