### ISSUE TITLE
Changing display names

### ISSUE THREAD

**Issue by EvaSchlunke** [pdiveris/sixacts#189]
Users logged in using other social media accounts are unable to access their six acts account profile to change display name.

As a short term solutions can we manually change this for them through the nova database?
3 display names to change immediately:
Simon Youel > change display name to **Positive Money**
![userID20](https://user-images.githubusercontent.com/53023979/63359511-c756a100-c364-11e9-9c7b-ca9798fcb360.JPG)

Ali > change display name to **Rethinking Economics**
![UserID13](https://user-images.githubusercontent.com/53023979/63359586-e8b78d00-c364-11e9-9e42-4475ea5807d0.JPG)

Kyle Poole > change display name to **Extinction Rebellion**
![userID11](https://user-images.githubusercontent.com/53023979/63359664-084eb580-c365-11e9-88ba-356bbcb5770f.JPG)

Note: I have attempted to change the display name for userID13 which appears as Rethinking Economics in the nova database, but still displays as Ali on the site.

**Comment by pdiveris** [comment]
* Use nova
* When they login using their social network credentials they get full access to their profile
* Everyone can change their password by simply going to the login page and clicking "forgot password"
* Please rephrase /elaborate /explain

This works exactly as it is designed to. Quite happy to revise design, for example adding a big profile link to home page. Broken icon certainly needs fixing and I am actually working on it, as it happens.

But, the bug described ain't not.
