### ISSUE TITLE
User didn't complete registration but managed to log in and submit proposals using Manc FoE account!

### ISSUE THREAD

**Issue by EvaSchlunke** [pdiveris/sixacts#190]
There is no record of an account registered for Alex Cooper, yet he managed to login and submit 6 proposals which appear on the site as posted by Manchester Friends of the Earth.

These 6 proposals are:
![6proposals](https://user-images.githubusercontent.com/53023979/63360674-aee78600-c366-11e9-9eca-d2d267bc1bf0.JPG)

**Could we manually change the display name of these 6 proposals to 'Alex Cooper' as an immediate fix and investigate the cause after that?**

It's fairly serious that this gets fixed urgently because Friends of the Earth are concerned that several of the proposals submitted in their name are outside FoE campaign policy areas.

**Comment by pdiveris** [comment]
I am looking at it now.

**Comment by pdiveris** [comment]
So, what is he loggin in as? And could it be that he's using a compyter previously used by a FoE user?

**Comment by pdiveris** [comment]
I need his email address - do you have it?
