### ISSUE TITLE
Add a 'do not reply to this message' to automated email user receives when registering account

### ISSUE THREAD

**Issue by EvaSchlunke** [pdiveris/sixacts#192]
![donotreply](https://user-images.githubusercontent.com/53023979/63445369-23d2c280-c430-11e9-9282-82fb753664d3.JPG)

I have just been dealing with a user who replied to this email with questions about the site. Obviously I didn't receive her email.

**Comment by pdiveris** [comment]
Do you want to reeive a copy, or just make it donotrepy?
