### ISSUE TITLE
Direct user to sign in before their vote can be added.

### ISSUE THREAD

**Issue by EvaSchlunke** [pdiveris/sixacts#193]
Users who land on the site and attempt to vote without logging in need reminding that they need to register/sign-in before their vote/dislike can be added.

Can we either:
a) add a pop-up message for when a user clicks on vote/dislike/propose an act reminding them to log in before they can perform that task
b) automatically redirect user to the log-in window when these buttons are clicked on by a non-signed-in user.

**Comment by pdiveris** [comment]
Will a popup. Consider done.

**Comment by pdiveris** [comment]
Added a popup!

**Comment by EvaSchlunke** [comment]
I have logged out and when I try to vote nothing happens... Not seeing pop-up...

**Comment by pdiveris** [comment]
Oh no.
