### ISSUE TITLE
Operation 'Fine-tooth-comb'

### ISSUE THREAD

**Issue by EvaSchlunke** [pdiveris/sixacts#199]
**There are multiple parts to this issue, but the overall objective is to refine all current functions and features of the website, add some minor text updates and other additions**

1. Add sign-in link:  https://www.sixacts.org/signin to print preview using a button 'Sign-in to vote for this proposal' or just 'Sign-in to vote'.
This should provide an interaction point to enter the site when people click on the print-preview link (as shared by users on facebook or other social media)

2 a) Replace the print-view icon with a 'share link' or 'get link' icon. This needs to communicate to the user that a unique URL for their proposal will be generated, which they can then sweep, copy and share in social media posts.
  b) Move position of the new 'share link' or 'get link' icon to right-hand side of 'dislikes' button, so that all interactive options (vote, dislike, share link) are grouped together clearly. _The current position of the print-view icon is a bit ambiguously placed - and it can be confused as belonging to the proposal below, rather than the proposal above._

3. Remove share via facebook and twitter icons from individual proposals - and just leave the new 'share link' or 'get link' icon to replace these. 

The share directly on fbook and twitter features are problematic if they don't allow for a sign-in button to be carried with the preview that gets shared.  Let's just lose these and keep it simple by giving users just one option to generate a unique link for their proposal - the 'share link' or 'get link' icon.

4. Remove the 'Current Document' filter option - It's better if we control this ourselves. **Really sorry to request removal after all the fuss we made** about this option... We think it's confusing and best to remove.  _All other filter options - 'most recent', 'most votes' 'most disliked' are excellent, please keep these as they are._

5. Update text for 'About'
[About_3rd Sept.pdf](https://github.com/pdiveris/sixacts/files/3572131/About_3rd.Sept.pdf)

6. Update text for 'Privacy policy' (edits are mostly single words or phrases and are in red for easy identification)
[Six Acts Privacy Policy update 27th Aug.pdf](https://github.com/pdiveris/sixacts/files/3556221/Six.Acts.Privacy.Policy.update.27th.Aug.pdf)

7. Update text for 'Terms of Service' (edits are mostly single words or phrases and are in red for easy identification)
[Terms of Service update 27th Aug.pdf](https://github.com/pdiveris/sixacts/files/3556228/Terms.of.Service.update.27th.Aug.pdf)

8. Add new text doc to homepage menu called _Why Six Acts?_
[Why.pdf](https://github.com/pdiveris/sixacts/files/3556320/Why.pdf)
Position this in menu bar between _9 Rules for the 6 Acts_ and _Register_

9. Add audio file to homepage 
[Salford City Radio interview.zip](https://github.com/pdiveris/sixacts/files/3556314/Salford.City.Radio.interview.zip)
Position audio file icon in left hand side vertical menu below social icons.
Add new 
title _MEDIA_.
Use same format for title as _TAGS, VIEW BY_ and _SIX ACTS ON SOCIAL_
If possible to add caption or label to the audio file - 'Paul Fitzgerald talking to Salford City Radio about the Six Acts project.'

**Comment by EvaSchlunke** [comment]
Note: Updated pdf added to replace previous attachment for 'About' text. (About_3rd Sept.pdf is now the the current doc)

**Comment by pdiveris** [comment]
Superseded.
