### ISSUE TITLE
Operation FTC Division 1 - Urgent updates to project info and 'share' function

### ISSUE THREAD

**Issue by EvaSchlunke** [pdiveris/sixacts#200]
**These are the top priority updates, urgently needed so that new traffic to the site will interact and share proposal and have the most up to date information about the project**
_Pulled from issue #199:_ 
    
1.Add sign-in link: https://www.sixacts.org/signin to print preview using a button 'Sign-in to vote for this proposal' or just 'Sign-in to vote'.
_We need to provide an interaction point to enter the site when people click on the print-preview link (as shared by users on facebook or other social media)_

2 a) Replace the print-view icon with a 'share link' or 'get link' icon. This needs to communicate to the user that a unique URL for their proposal will be generated, which they can then sweep, copy and share in social media posts.
b) Move position of the new 'share link' or 'get link' icon to right-hand side of 'dislikes' button, so that all interactive options (vote, dislike, share link) are grouped together clearly. The current position of the print-view icon is a bit ambiguously placed - and it can be confused as belonging to the proposal below, rather than the proposal above.

3.Remove share via facebook and twitter icons from individual proposals - and just leave the new 'share link' or 'get link' icon to replace these.
_The share directly on fbook and twitter features are problematic if they don't allow for a sign-in button to be carried with the preview that gets shared. Let's just lose these and keep it simple by giving users just one option to generate a unique link for their proposal - the 'share link' or 'get link' icon._

4.Remove the 'Current Document' filter option - It's better if we control this ourselves. Really sorry to request removal after all the fuss we made about this option... We think it's confusing and best to remove. All other filter options - 'most recent', 'most votes' 'most disliked' are excellent, please keep these as they are.

5.Update text for 'About'
[About_3rd Sept.pdf](https://github.com/pdiveris/sixacts/files/3576216/About_3rd.Sept.pdf)

 6.Update text for 'Privacy policy' 
   (edits are mostly single words or phrases and are in red for   easy identification)
  [Six Acts Privacy Policy update 27th Aug.pdf](https://github.com/pdiveris/sixacts/files/3576218/Six.Acts.Privacy.Policy.update.27th.Aug.pdf)

 7. Update text for 'Terms of Service' 
(edits are mostly single words or phrases and are in red for easy identification)
 [Terms of Service update 27th Aug.pdf](https://github.com/pdiveris/sixacts/files/3576223/Terms.of.Service.update.27th.Aug.pdf)

**Comment by pdiveris** [comment]
OK, sounds good.

**Comment by EvaSchlunke** [comment]
Can updating the 'About' page be the priority here please? It's a bit embarrassing that it still has pre-launch info.

**Comment by diverispetros** [comment]
Sorry I've been inundated with new job and also been ill. Will look to it all over the weekend.

**Comment by EvaSchlunke** [comment]
Thanks! Hope job's going well.
