### ISSUE TITLE
proposals: enforce 100 word validation

### ISSUE THREAD

**Issue by pdiveris** [pdiveris/sixacts#31]
##### Make sure proposals do not exceed 100 words. 
* Add server side validation
* Show word counter and red error like the one seen in twitter (bot for words, not characters)

**Comment by pdiveris** [comment]
This is now completed, with a fabulous little realtime word counter which turns red when you hit 90 words. It doesn't count some obvious stopwords such as "a", "the", "we" etc. See attached screenshot.

```
    const stopwords = {"a":1,"all":1,"an":1,"and":1,"are":1,"as":1,"at":1,"be":1,"but":1,
        "by":1,"can":1,"do":1,"for":1,"from":1,"had":1,"have":1,"if":1,"in":1,"is":1,
        "it":1,"me":1,"my":1,"no":1,"not":1,"of":1,"on":1,"or":1,"our":1,"s":1,"so":1,
        "t":1,"that":1,"the":1,"their":1,"they":1,"this":1,"to":1,"us":1,"was":1,"we":1,
        "who":1,"with":1,"you":1
    };

```
![Screenshot 2019-07-28 at 01 19 18](https://user-images.githubusercontent.com/1022373/62000740-90c79680-b0d6-11e9-96c6-4f098719a8b8.png)

**Comment by EvaSchlunke** [comment]
Excellent!
