### ISSUE TITLE
launch: add a coming soon page (splash) as per request

### ISSUE THREAD

**Issue by pdiveris** [pdiveris/sixacts#39]
A splash page has been requested and designed and can be [seen](http://peterloomassacre.org/sixacts.html?fbclid=IwAR3CWX75SyMcGew2_BE8_GNINPCS3aXZIh78CiuOftsR8IPcsZ_MvrRicWE) in Peterloomasacre webite.

My intention is to thorw this page as square element falling, bouncing snd finally. Before this happens we need to
* Add an entry point `/welcome`
* Add the corresponding view resources.

**Comment by EvaSchlunke** [comment]
Text for holding page animation message:

<font size="3.5"> <i>The Six Acts project is an online platform to crowd-source radical ideas for improving and redesigning the way we practice democracy in the 21st century.</i> 
<br>
<br><font size="3.5"> <b>The poll will open for submissions and voting at 4pm on the 17th August 2019.</b></font> 
<br>
<br><font size="2.5">We look forward to your participation. In the meantime, please familiarise yourself with the information on this page which explains how the poll will be conducted and help you ensure that your proposals are submitted correctly.
<br>
<br>Get thinking, get your acts together, and we'll see you back here on the 17th August!</font>

(End text)

I have removed the instructions for voting and submitting proposlas that were included with this message in the original draft. I feel they are unecessarily complicated and intimidating for a holding page message.

If we feel they are necessary to add somewhere to the site, I suggest we add them in the same format as the 'Catergories Explained' and '9 Rules' documents, but I feel confident that the site is reasonably self-explanatory and these procedures will be obvious to users...

**Comment by pdiveris** [comment]
Thanks for the clarification.
