### ISSUE TITLE
css: add layout without navbar, footer, header etc. to be used with modals

### ISSUE THREAD

**Issue by pdiveris** [pdiveris/sixacts#42]
In the context of dealing with #39, it is quite possible that we want the splash page to not contain the standard sections seen in the rest of the ite, i.e. header, navbar, sidebar, footer etc. A layout is therefore required to contain all the standard styles, fonts, libraries etc bit none of the sections.

Whether the splash page will be a modal one or not will have to be discussed at a later stage, post demo however, a "naked" layout is required nevertheless.

**Comment by EvaSchlunke** [comment]
Given that the splash animated message refers to 'information on this page' I suggest we keep essential information

**Comment by pdiveris** [comment]
Erm.. why did you re-open this? It has been superceeded by #39 wihich I am incidentally about to close. This is an internal ticket relating to the format of the content of the splash screen, not whether there will be a splash screen (which is what I am owking on now!)

**Comment by EvaSchlunke** [comment]
Clarifications:
1. Blurb contained in the 'About' section is the intended text for 'holding page' animated message
2. Given that the animated message refers to 'information on this page' I suggest we keep links to the 'About', 'Categories Explained' and '9 Rules' sections visible on the holding page (in navbar?)
3. I Agree that apart from the above links and the splash animation message, holding page can be  'naked'

**Comment by EvaSchlunke** [comment]
Further clarification:
4. I will send you new text for the 'About' section

**Comment by pdiveris** [comment]
Yes sure, but we can have the splash in the middle with only two or three of the main site's navbar items enabled, it's a lot of work for a temporary need. I will simply add the links to the two items IN the splash screen.

Incidentally we have two versions of the splash page content:
* A full webs site one https://beta.sixacts.org/about where the links are all there and
* A naked one to be shown in the middle in a modal kind of splash thingy https://beta.sixacts.org/intro

As you can see I have already provided for both scenarios, so I am closing this and we'll migrate the final conversation about the splash page back to #39 when I am done in the next two to three hours!

**NB:** If you send me text forabout, I will be still keeping a non naked version of the splash, I will simply migrate it to another url, e.g. `/fullintro` or something. Bear in mind that we do not *have* to have an about page, it was in the original menu by habit (most sites carry one.) If all we need to say has already been said in the two links provided then we can just remove it.
