### ISSUE TITLE
splash: discuss which elements of the navbar are clickable

### ISSUE THREAD

**Issue by pdiveris** [pdiveris/sixacts#45]
Despite my previous assertion, the _navbar_ is still visible after all, due to the mechanism I used to implement the splash screen as I was/am running out of time.

That shouldn't be a problem per se, as we can disable any menu item we want.

Could you therefore plese respond to this pointing at the menu items you want disabled/enabled?

You should be able to see the menu items now, even with the splash screen being on, however, if you want to disable the splash screen altogether (e.g. for testing) then you should be able to that by adding `?nosplash=please` to the URL you are visiting.

**Comment by pdiveris** [comment]
By the way, whilst the menu items for `home` (voting) and `propose` can and will be greyed out from the menu, one can still in theory go to propose directy, by visisting the URL https://oursite/propose. Do you want me to redirect this page to the home/splash during the countdown?

**Comment by pdiveris** [comment]
OK, so after recent discussion until we go live on `August 17, 2019 16:00:00` we'll be 

### leaving active the following 
* About
* Categories Explained 
* 9 Rules for the 6 Acts
* Terms
* Privacy

### disabling
* Register
* Sign In
* Log in
* Propose

**Comment by EvaSchlunke** [comment]
Affirmative!
