### ISSUE TITLE
static: change the content of about page

### ISSUE THREAD

**Issue by pdiveris** [pdiveris/sixacts#47]
Change the content of the About page to reflect the attached PDF

[about.pdf](https://github.com/pdiveris/sixacts/files/3439486/about.pdf)

**Comment by pdiveris** [comment]
Erm... in your text, you state

It is also important that you are completely happy with your proposal at the time you submit it because _once submitted you will not be able to edit it_. **(Only delete and replace it.)**

How do you mean delete and replace? There is no such functionality for people with no access to the backend?! And most voters don't have that access..

**Comment by EvaSchlunke** [comment]
They would have to email us directly and request it is deleted. 
Not a biggy to get stucck on now though. Can we review this later pre-launch?
Text is fine for now.
Thank you x

**Comment by pdiveris** [comment]
Aw, I wasn't really thinking of doing anything, I was just curious as to what you meant by that.

Cheers,
Petros Diveris
Sent from Manchester with utter care

E: petros@diveris.org (mailto:petros@diveris.org)
P: +44 7771 608 617 (tel:+44%207771%20608%20617)+44 (0) 161 249 0536 (tel:+44%20(0)%20161%20249%200536) (Fax)
W: http://www.diveris.org

**Comment by EvaSchlunke** [comment]
Its a good point though. One of those things that I hadn't quite thought through yet...
