### ISSUE TITLE
fix: finish off the user profile section

### ISSUE THREAD

**Issue by pdiveris** [pdiveris/sixacts#48]
#### User profile remaining tasks
* Make sure the password change works and it happens (it probably does)
* Wire in the avatar upload mechanism
* Add screen name
* Add switches for privacy

**Comment by EvaSchlunke** [comment]
If user signs in with facebook/twitter/google account their username is carried with that account and they don't get an opportunity to change/edit the way their username appears on the site.

Is it possible to add 1 more step to the sign-in process that asks for the username that they want to appear on the sixacts site?

**Comment by pdiveris** [comment]
Both were already there
1. It's called display name - I've added explainer is it was not obvious, obviously.
2. They've always been able to that by visiting the URL in the email, or by clicking on their photo at the to right..

**Comment by pdiveris** [comment]
Closed by accident,

**Comment by pdiveris** [comment]
Why are you re-opening this? I just made everything working.
See notes in other ticket. Actually no, here's the notes:

* The long window is chrome, is not me.
* Click on the top right where it says login
* Type in your email and password.
* Click on the icon on the tot right.

You are in your profile. I just logged in as you

**Comment by EvaSchlunke** [comment]
Clicking on photo brings up this window.
![change display name2](https://user-images.githubusercontent.com/53023979/63202305-fd540680-c080-11e9-8390-c2cb41cfee37.JPG)

If I change display name without entering password I get this window.
![change display name](https://user-images.githubusercontent.com/53023979/63202309-01802400-c081-11e9-9e21-be0aa30fe31a.JPG)

**Comment by pdiveris** [comment]
There is no photo, I took it out. Can you please reload the page? Shift reload if necessary.
The page works. I've just logged in as you and Paul 10 times now.

Top right.
Petros Diveris
Sent from Manchester with utter care

E: petros@diveris.org (mailto:petros@diveris.org)
P: +44 7771 608 617 (tel:+44%207771%20608%20617)+44 (0) 161 249 0536 (tel:+44%20(0)%20161%20249%200536) (Fax)
W: http://www.diveris.org

**Comment by pdiveris** [comment]
You mean the broken image in the top right?

Yes - it brings the.. profile page.
Petros Diveris
Sent from Manchester with utter care

E: petros@diveris.org (mailto:petros@diveris.org)
P: +44 7771 608 617 (tel:+44%207771%20608%20617)+44 (0) 161 249 0536 (tel:+44%20(0)%20161%20249%200536) (Fax)
W: http://www.diveris.org

**Comment by pdiveris** [comment]
Oh I see. Did you type a password in?

I've disabled it completely now - try as it is now.
Petros Diveris
Sent from Manchester with utter care

E: petros@diveris.org (mailto:petros@diveris.org)
P: +44 7771 608 617 (tel:+44%207771%20608%20617)+44 (0) 161 249 0536 (tel:+44%20(0)%20161%20249%200536) (Fax)
W: http://www.diveris.org

**Comment by pdiveris** [comment]
OK, now I broke it. I''ll be back when I find out what's going on.

Petros Diveris
Sent from Manchester with utter care

E: petros@diveris.org (mailto:petros@diveris.org)
P: +44 7771 608 617 (tel:+44%207771%20608%20617)+44 (0) 161 249 0536 (tel:+44%20(0)%20161%20249%200536) (Fax)
W: http://www.diveris.org

**Comment by pdiveris** [comment]
Yes, no, I mean it's OK if you don't touch the password (which is what I was working on.)

Can you shift reload and try the whole sebang?
Petros Diveris
Sent from Manchester with utter care

E: petros@diveris.org (mailto:petros@diveris.org)
P: +44 7771 608 617 (tel:+44%207771%20608%20617)+44 (0) 161 249 0536 (tel:+44%20(0)%20161%20249%200536) (Fax)
W: http://www.diveris.org
