### ISSUE TITLE
Fix unstable return to homepage splash animation

### ISSUE THREAD

**Issue by EvaSchlunke** [pdiveris/sixacts#73]
![image](https://user-images.githubusercontent.com/53023979/62211637-fb0e5e80-b396-11e9-937f-57062e3bae22.png)

Homepage splash animation does not always appear when:
a) Clicking 'home' after visiting static page eg. 'Categories explained'
b) Clicking browser back arrow after visiting static page eg. 'Categories explained'
c) Manually entering 'www.sixacts.org' into browser (not directed to site through a link)

The problem appears to be unstable and a bit random - sometimes works, sometimes not.

The attached screengrab shows the 'locked' homepage that appears. User is unable to return to the homepage with splash animation once arriving at the 'locked' homepage.

**Comment by pdiveris** [comment]
Yes I saw it now too. Trouble is, it seems random which makes it hard for me to figure out what the hell is happening there. I am looking to it.

**Comment by EvaSchlunke** [comment]
Another clue maybe... Hitting reload on splash animation takes it to 'locked' blank homepage.

Perhaps blank homepage is somehow linked to what happens when page reloads?

**Comment by pdiveris** [comment]
It actually had to do with the background loading of the various scripts that drive the "very simpl" user interface and interaction. I think I've got it sorted, just nw!

**Comment by EvaSchlunke** [comment]
Yes!! Beautiful!
